version: "2"
networks:
  default:
    external:
      name: amp-swarm
services:
  test:
    build: .
    image: amp-kafka
    environment:
      DEBUG: app*
    volumes:
      - ./dist:/usr/src/app/dist
    command: "node_modules/.bin/mocha ./dist/test"
